const BusStopName: string[] = [
    'Central',
    'Admiralty',
    'Wan Chai',
    'Causeway Bay',
    'Tin Hau',
    'Fortress Hill',
    'North Point',
    'Quarry Bay',
    'Tai Koo',
    'Sai Wan Ho',
    'Shau Kei Wan',
    'Heng Fa Chuen',
    'Chai Wan',
    'Siu Sai Wan',
    'Kennedy Town',
    'Shek Tong Tsui',
    'Sai Ying Pun',
    'Western Market',
    'Sheung Wan',
    'Mid-Levels',
    'Happy Valley',
    'Aberdeen',
    'Ap Lei Chau',
    'Wong Chuk Hang',
    'Ocean Park',
    'Repulse Bay',
    'Stanley',
    'Cyberport',
    'Pok Fu Lam',
    'The Peak',
    'Lei Tung',
    'South Horizons',
];

export default BusStopName;
